/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PAT;

/*
Class MainGUI
Allows an interface for the user to access all the screens that they are allowed to use
*/
public class MainGUI extends javax.swing.JFrame {
    String userType = ""; //The type of the current user
    String userWelcome = ""; //The welcome message displaye on the top of the screen
    private boolean helpEnabled = false; //The state of the help boxes
    /*
    Constructor Method
    Used to create an instance of the MainGUI class
    @parameters: String user type, String user welcome message
    @return: none
    */
    public MainGUI(String _userType, String _userWelcome) {
        userType = _userType;
        userWelcome = _userWelcome;
        initComponents();
        setRestrictions(userType); //enable only the buttons the user is allowed to use
        setHelp(false); //turn help boxes off
        //display welcome message
        lblWelcomeMsg.setText("Welcome " + _userWelcome);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblMenu = new javax.swing.JLabel();
        lblWelcomeMsg = new javax.swing.JLabel();
        btnMainHelp = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        btnAthleteGUI = new javax.swing.JButton();
        btnStockGUI = new javax.swing.JButton();
        btnMealGUI = new javax.swing.JButton();
        btnAdminGUI = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaAdminHelp = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaAthHelp = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAreaStockHelp = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtAreaMealHelp = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblMenu.setBackground(new java.awt.Color(255, 255, 255));
        lblMenu.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblMenu.setText("                       MENU");
        lblMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        lblWelcomeMsg.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblWelcomeMsg.setText("Welcome");

        btnMainHelp.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnMainHelp.setText("HELP");
        btnMainHelp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnMainHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMainHelpActionPerformed(evt);
            }
        });

        btnLogOut.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnLogOut.setText("LOGOUT");
        btnLogOut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        btnAthleteGUI.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAthleteGUI.setText("Athletes");
        btnAthleteGUI.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        btnAthleteGUI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAthleteGUIActionPerformed(evt);
            }
        });

        btnStockGUI.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnStockGUI.setText("Stock");
        btnStockGUI.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        btnStockGUI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStockGUIActionPerformed(evt);
            }
        });

        btnMealGUI.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnMealGUI.setText("Meal");
        btnMealGUI.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        btnMealGUI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMealGUIActionPerformed(evt);
            }
        });

        btnAdminGUI.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAdminGUI.setText("Admin");
        btnAdminGUI.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        btnAdminGUI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminGUIActionPerformed(evt);
            }
        });

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txtAreaAdminHelp.setEditable(false);
        txtAreaAdminHelp.setColumns(20);
        txtAreaAdminHelp.setRows(5);
        txtAreaAdminHelp.setText("Admin screen is used\nto access info on\nusers and edit users\nand their info.");
        txtAreaAdminHelp.setAutoscrolls(false);
        txtAreaAdminHelp.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane1.setViewportView(txtAreaAdminHelp);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txtAreaAthHelp.setEditable(false);
        txtAreaAthHelp.setColumns(20);
        txtAreaAthHelp.setRows(5);
        txtAreaAthHelp.setText("Athlete screen is\nused to access info\non players and edit\nathletes and their\ninfo.");
        txtAreaAthHelp.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane2.setViewportView(txtAreaAthHelp);
        txtAreaAthHelp.getAccessibleContext().setAccessibleName("");
        txtAreaAthHelp.getAccessibleContext().setAccessibleDescription("");

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txtAreaStockHelp.setEditable(false);
        txtAreaStockHelp.setColumns(20);
        txtAreaStockHelp.setRows(5);
        txtAreaStockHelp.setText("Stock screen is used\nto manage stock \nlevels and also \nplace and receive\norders.");
        txtAreaStockHelp.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane3.setViewportView(txtAreaStockHelp);

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txtAreaMealHelp.setEditable(false);
        txtAreaMealHelp.setColumns(20);
        txtAreaMealHelp.setRows(5);
        txtAreaMealHelp.setText("Meal screen is used\nwhen preparing a \nmeal to record stock\ndrop and the amount\nneeded for hostel");
        txtAreaMealHelp.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane4.setViewportView(txtAreaMealHelp);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnMainHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAthleteGUI, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnStockGUI, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMealGUI, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAdminGUI, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(255, 255, 255))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblWelcomeMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(173, 173, 173))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMainHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblWelcomeMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(btnAthleteGUI, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(btnStockGUI, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnMealGUI, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAdminGUI, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /*
    Method Athlete button
    Opens the Athlete GUI
    */
    private void btnAthleteGUIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAthleteGUIActionPerformed
        dispose();
        AthleteGUI ath = new AthleteGUI(userType, userWelcome);
        ath.setVisible(true);
    }//GEN-LAST:event_btnAthleteGUIActionPerformed
    /*
    Method of the Stock Button
    Opens the Stock GUI
    */
    private void btnStockGUIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStockGUIActionPerformed
        dispose();
        StockGUI sto = new StockGUI(userType, userWelcome);
        sto.setVisible(true);
    }//GEN-LAST:event_btnStockGUIActionPerformed
    /*
    Method of the Meal button
    Opens the Meal GUI
    */
    private void btnMealGUIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMealGUIActionPerformed
        dispose();
        MealGUI mel = new MealGUI(userType, userWelcome);
        mel.setVisible(true);
    }//GEN-LAST:event_btnMealGUIActionPerformed
    /*
    Method of the admin button
    Opens the Admin GUI
    */
    private void btnAdminGUIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminGUIActionPerformed
        dispose();
        AdminGUI adm = new AdminGUI(userType, userWelcome);
        adm.setVisible(true);
    }//GEN-LAST:event_btnAdminGUIActionPerformed
    /*
    Method of the Logout button
    Returns to the login screen
    */
    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        dispose();
        LoginGUI log = new LoginGUI();
        log.setVisible(true);
    }//GEN-LAST:event_btnLogOutActionPerformed
    /*
    Method of the help button
    Enables or disables the help boxes
    */
    private void btnMainHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMainHelpActionPerformed
        if(helpEnabled == false){
            setHelp(true);
            helpEnabled = true;
        }else{
            setHelp(false);
            helpEnabled = false;
        }
    }//GEN-LAST:event_btnMainHelpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUI("", "").setVisible(true);
            }
        });
    }
    /*
    Method setHelp
    Sets the visibillity of the help boxes
    @parameters: Boolean the state of the help boxes
    @return: none
    */
    private void setHelp(boolean enabled){
        txtAreaAthHelp.setVisible(enabled);
        txtAreaMealHelp.setVisible(enabled);
        txtAreaStockHelp.setVisible(enabled);
        txtAreaAdminHelp.setVisible(enabled);
    }
    /*
    Method setRestrictions
    Determines what GUIs the user can acces based on their user type
    @parameters: string user type
    @return: none
    */
    private void setRestrictions(String type){
        //If user is apart of the kitchen staff
        if(type.equals("Kitchen")){
            btnAthleteGUI.setEnabled(false);
            btnAdminGUI.setEnabled(false);
        //if the user is apart of the coaching staff
        }else if (type.equals("Coaching")){
            btnStockGUI.setEnabled(false);
            btnMealGUI.setEnabled(false);
            btnAdminGUI.setEnabled(false);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdminGUI;
    private javax.swing.JButton btnAthleteGUI;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnMainHelp;
    private javax.swing.JButton btnMealGUI;
    private javax.swing.JButton btnStockGUI;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblMenu;
    private javax.swing.JLabel lblWelcomeMsg;
    private javax.swing.JTextArea txtAreaAdminHelp;
    private javax.swing.JTextArea txtAreaAthHelp;
    private javax.swing.JTextArea txtAreaMealHelp;
    private javax.swing.JTextArea txtAreaStockHelp;
    // End of variables declaration//GEN-END:variables
}
